services:
    db:
        build:
            context: ./db-service
            dockerfile: Dockerfile
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - volume_db:/var/lib/postgresql/data
        networks:
            - network_private
        container_name: db
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    app:
        depends_on:
            - db
        build:
            context: ./app-service
            dockerfile: Dockerfile
        restart: always
        volumes:
            - volume_app:/Conkueror
        networks:
            - network_private
        container_name: app
        environment:
            - IS_CONTAINER=${IS_CONTAINER}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}


volumes:
    volume_db:
    volume_app:

networks:
    network_private:
  